#!/usr/bin/env bash
# seed-test-data.sh — Seed dev database with test fixtures via API
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
API_URL="${API_URL:-http://localhost:8000/api/v1}"
FIXTURES_FILE="$PROJECT_DIR/apps/web/e2e/functional/fixtures/test-constants.ts"

echo "Seeding test data via ${API_URL}..."

# Step 1: Create test user via Supabase (or use existing)
echo "  → Ensuring test user exists (functional-test@va.dev)"

# Step 2: Get auth token
TOKEN=$(curl -s -X POST "${API_URL}/auth/token" \
  -H "Content-Type: application/json" \
  -d '{"email":"functional-test@va.dev","password":"TestPass123!"}' \
  | python3 -c "import sys,json; print(json.load(sys.stdin).get('access_token',''))" 2>/dev/null || echo "")

if [ -z "$TOKEN" ]; then
    echo "  ⚠ Could not get auth token. Using dev bypass header."
    AUTH_HEADER="X-Dev-User: functional-test@va.dev"
else
    AUTH_HEADER="Authorization: Bearer ${TOKEN}"
fi

# Helper: API call with tenant header
api() {
    local method="$1" path="$2"
    shift 2
    curl -s -X "$method" "${API_URL}${path}" \
        -H "Content-Type: application/json" \
        -H "X-Tenant-ID: test-tenant-001" \
        -H "$AUTH_HEADER" \
        "$@"
}

# Step 3: Seed baseline from marketplace template
echo "  → Creating baseline from marketplace template"
TEMPLATES=$(api GET "/marketplace/templates")
FIRST_TEMPLATE_ID=$(echo "$TEMPLATES" | python3 -c "import sys,json; ts=json.load(sys.stdin); print(ts[0]['id'] if ts else '')" 2>/dev/null || echo "")

if [ -n "$FIRST_TEMPLATE_ID" ]; then
    BASELINE_RESP=$(api POST "/marketplace/templates/${FIRST_TEMPLATE_ID}/use" \
        -d "{\"label\":\"Functional Test Baseline\",\"fiscal_year_end\":\"2025-12-31\"}")
    BASELINE_ID=$(echo "$BASELINE_RESP" | python3 -c "import sys,json; print(json.load(sys.stdin).get('id',''))" 2>/dev/null || echo "seed-baseline-001")
else
    BASELINE_ID="seed-baseline-001"
fi
echo "  → Baseline ID: ${BASELINE_ID}"

# Step 4: Create draft from baseline
echo "  → Creating draft"
DRAFT_RESP=$(api POST "/drafts/create" -d "{\"baseline_id\":\"${BASELINE_ID}\",\"label\":\"Functional Test Draft\"}")
DRAFT_ID=$(echo "$DRAFT_RESP" | python3 -c "import sys,json; print(json.load(sys.stdin).get('id',''))" 2>/dev/null || echo "seed-draft-001")
echo "  → Draft ID: ${DRAFT_ID}"

# Step 5: Execute a run
echo "  → Executing run"
RUN_RESP=$(api POST "/runs/execute" -d "{\"draft_id\":\"${DRAFT_ID}\",\"mode\":\"deterministic\"}")
RUN_ID=$(echo "$RUN_RESP" | python3 -c "import sys,json; print(json.load(sys.stdin).get('id',''))" 2>/dev/null || echo "seed-run-001")
echo "  → Run ID: ${RUN_ID}"

# Step 6: Create budget
echo "  → Creating budget"
BUDGET_RESP=$(api POST "/budgets/create" -d "{\"label\":\"FY2025 Test Budget\",\"baseline_id\":\"${BASELINE_ID}\"}")
BUDGET_ID=$(echo "$BUDGET_RESP" | python3 -c "import sys,json; print(json.load(sys.stdin).get('id',''))" 2>/dev/null || echo "seed-budget-001")
echo "  → Budget ID: ${BUDGET_ID}"

# Step 7: Create board pack
echo "  → Creating board pack"
BP_RESP=$(api POST "/board-packs/create" -d "{\"run_id\":\"${RUN_ID}\",\"title\":\"Test Board Pack\"}")
BOARD_PACK_ID=$(echo "$BP_RESP" | python3 -c "import sys,json; print(json.load(sys.stdin).get('id',''))" 2>/dev/null || echo "seed-bp-001")
echo "  → Board Pack ID: ${BOARD_PACK_ID}"

# Step 8: Get workflow template ID
echo "  → Fetching workflow templates"
WF_TEMPLATES=$(api GET "/workflows/templates")
WF_TEMPLATE_ID=$(echo "$WF_TEMPLATES" | python3 -c "import sys,json; ts=json.load(sys.stdin); print(ts[0]['id'] if ts else '')" 2>/dev/null || echo "seed-wf-tpl-001")
echo "  → Workflow Template ID: ${WF_TEMPLATE_ID}"

# Step 9: Write IDs to test-constants.ts
echo "  → Writing seeded IDs to fixtures"
cat > "$FIXTURES_FILE" << EOF
// test-constants.ts — Auto-generated by seed-test-data.sh
// DO NOT EDIT MANUALLY — re-run seed script to regenerate

export const TEST_USER = {
  email: 'functional-test@va.dev',
  password: 'TestPass123!',
};

export const SEEDED_IDS = {
  tenantId: 'test-tenant-001',
  baselineId: '${BASELINE_ID}',
  draftId: '${DRAFT_ID}',
  runId: '${RUN_ID}',
  afsEngagementId: '',
  budgetId: '${BUDGET_ID}',
  covenantId: '',
  boardPackId: '${BOARD_PACK_ID}',
  workflowTemplateId: '${WF_TEMPLATE_ID}',
};

export const BASE_URL = '${BASE_URL:-http://localhost:3000}';
export const API_URL = '${API_URL:-http://localhost:8000/api/v1}';
EOF

echo ""
echo "✓ Test data seeded successfully."
