"""Email delivery service using SendGrid (H-03).

Provides ``send_board_pack_email`` for distributing board pack narratives to recipients.
Falls back to logging when SENDGRID_API_KEY is not configured (development mode).
"""

from __future__ import annotations

import html as html_mod
import json
import logging
from typing import Any

import httpx

from apps.api.app.core.settings import get_settings

logger = logging.getLogger(__name__)


class EmailError(Exception):
    """Raised when email delivery fails."""


async def send_board_pack_email(
    to_emails: list[str],
    pack_label: str,
    narrative_json: dict[str, Any] | str | None,
) -> dict[str, Any]:
    """Send a board pack narrative to one or more recipients via SendGrid.

    Returns ``{"sent": True, "recipients": [...]}`` on success.
    Falls back to logging when ``SENDGRID_API_KEY`` is not set.
    """
    settings = get_settings()

    if not to_emails:
        return {"sent": False, "recipients": [], "reason": "no_recipients"}

    if not settings.sendgrid_api_key:
        logger.warning(
            "SENDGRID_API_KEY not configured — skipping email delivery (dev mode). "
            "Would send board pack '%s' to %s",
            pack_label,
            to_emails,
        )
        return {"sent": False, "recipients": to_emails, "reason": "sendgrid_not_configured"}

    # Build readable narrative from JSON
    narrative = _format_narrative(narrative_json)

    html_body = _build_html(pack_label, narrative)
    plain_body = _build_plain(pack_label, narrative)

    personalizations = [{"to": [{"email": e} for e in to_emails]}]

    payload = {
        "personalizations": personalizations,
        "from": {
            "email": settings.email_from_address,
            "name": settings.email_from_name,
        },
        "subject": f"Board Pack: {pack_label}",
        "content": [
            {"type": "text/plain", "value": plain_body},
            {"type": "text/html", "value": html_body},
        ],
    }

    async with httpx.AsyncClient() as client:
        resp = await client.post(
            "https://api.sendgrid.com/v3/mail/send",
            json=payload,
            headers={
                "Authorization": f"Bearer {settings.sendgrid_api_key}",
                "Content-Type": "application/json",
            },
            timeout=30.0,
        )

    if resp.status_code not in (200, 202):
        logger.error(
            "SendGrid API error %d: %s",
            resp.status_code,
            resp.text,
        )
        raise EmailError(f"SendGrid returned {resp.status_code}: {resp.text}")

    logger.info("Board pack '%s' emailed to %d recipients", pack_label, len(to_emails))
    return {"sent": True, "recipients": to_emails}


def _format_narrative(narrative_json: dict[str, Any] | str | None) -> dict[str, str]:
    """Parse narrative_json into a dict of section_name -> text."""
    if narrative_json is None:
        return {"executive_summary": "(No narrative generated yet.)"}
    if isinstance(narrative_json, str):
        try:
            narrative_json = json.loads(narrative_json)
        except (json.JSONDecodeError, TypeError):
            return {"executive_summary": narrative_json}
    if isinstance(narrative_json, dict):
        return {k: str(v) for k, v in narrative_json.items()}
    return {"executive_summary": str(narrative_json)}


def _build_html(pack_label: str, sections: dict[str, str]) -> str:
    """Build a simple HTML email body from board pack sections."""
    parts = [
        "<html><body>",
        f"<h1 style='color:#1a1a2e;'>Board Pack: {_esc(pack_label)}</h1>",
        "<hr/>",
    ]
    for title, body in sections.items():
        heading = title.replace("_", " ").title()
        parts.append(f"<h2 style='color:#16213e;'>{_esc(heading)}</h2>")
        # Wrap paragraphs
        for para in body.split("\n"):
            stripped = para.strip()
            if stripped:
                parts.append(f"<p>{_esc(stripped)}</p>")
    parts.append(
        "<hr/><p style='font-size:12px;color:#888;'>"
        "This board pack was generated by Virtual Analyst.</p>"
    )
    parts.append("</body></html>")
    return "\n".join(parts)


def _build_plain(pack_label: str, sections: dict[str, str]) -> str:
    """Build a plain-text email body from board pack sections."""
    lines = [f"Board Pack: {pack_label}", "=" * 40, ""]
    for title, body in sections.items():
        heading = title.replace("_", " ").title()
        lines.append(heading)
        lines.append("-" * len(heading))
        lines.append(body)
        lines.append("")
    lines.append("---")
    lines.append("This board pack was generated by Virtual Analyst.")
    return "\n".join(lines)


def _esc(text: str) -> str:
    """HTML-escape text for safe inclusion in email markup."""
    return html_mod.escape(text, quote=True)
